### ISSUE TITLE
Quest completion bugs 

### ISSUE THREAD

**Issue by cookieslap** [Alnarra/WaySouls#1]
So far both the 'The ultimate compass' and 'Let the ritual... begin' quests are not completing for me even though I have handcrafted the necessary items and spammed the complete button in the quest tracker. I even tried spawning in a copy of both items for good measure and this did not work either.

**Comment by Alnarra** [comment]
This will be fixed in version 0.0.7 of the Modpack, I have changed the quest from crafting to simply retrieval, I am unsure of why these two, in particular, weren't being detected. 

Thank you for bringing this to my attention

**Comment by cookieslap** [comment]
No problem, really loving the modpack but I guess I'll wait till 0.0.7 to play again as I really want to do blood magic. Those were the only 2 I found in that play session but it might be possible that the other books you needed to craft for the other mods like necromancy are bugged then too - just something to look out for :)

**Comment by Alnarra** [comment]
*nod* yeah the quest books be it HQM or better questing all seem to be super finicky with what they do and do not like to detect being crafted. A lot of the time it's just NBT values going south. I'm adding Millianre and Nature's Aura for 0.0.7 so as soon as I get a base questline for Abyssalcraft and one for Nature's Aura in place 0.0.7 should be ready

**Comment by cookieslap** [comment]
I don't know much about coding or anything but if you want a hand writing the quest lines feel free to hmu, I'm in your discord.

**Comment by Kobra** [comment]
It is impossible to complete quests with crafting tasks in new world (in my case allow cheats on? may be recreate world without cheats?)

p.s. - get version from FTB, and update from github

**Comment by Alnarra** [comment]
> It is impossible to complete quests with crafting tasks in new world (in my case allow cheats on? may be recreate world without cheats?)
> 
> p.s. - get version from FTB, and update from github

At least the version that's live on Github at the moment is in the /bq_admin edit mode from where I've been working on the quest. Might want to try /bq_admin edit and see if it goes back to it's non edit mode, I know in the past that's caused some issues. When I get a chance though I'll spin up a quick world in 0.0.7 ad see if I can't see what's causing it.

**Comment by Kobra** [comment]
oooo! yes! /bq_admin edit switch to non-edit mode and all works fine! Thanks!

**Comment by Alnarra** [comment]
With 0.0.7 now released this issue should be resolved, let me know if the behavior continues
