### ISSUE TITLE
Quest completion bugs V2 :D

### ISSUE THREAD

**Issue by cookieslap** [Alnarra/WaySouls#2]
The quest to craft parchment for Astral Sorcery doesn't detect completion. I'm no coder but as this is a crafting task and the way you craft with Astral Sorcery is not using a crafting table then that is probably why it won't complete? Guessing changing it to a submit quest will fix it like the other ones I reported.

**Comment by Alnarra** [comment]
Hmm that's odd, this is the parchment with the 4 paper around one Aquamarine right? That should be working, or rather it worked on the test server, let me check a bit more when I get a chance to see if I can't find the issue.

**Comment by cookieslap** [comment]
Hmm yeah that's the one. I'll try it again later if you would like.

**Comment by Alnarra** [comment]
typing /bq_admin edit doesn't do anything right (Just want to make sure)

**Comment by cookieslap** [comment]
Nothing changed than 'edit mode: on' appearing in chat. I tried crafting it again and it still didn't work. Although with the admin mode on I could obviously set it to complete to allow me to progress in the short time.

**Comment by Alnarra** [comment]
I figured it out :P 

This is now fixed 
![capture](https://user-images.githubusercontent.com/15974903/49553486-e0e2b600-f8c5-11e8-9d10-1ec56525ddc3.PNG)

**Comment by Alnarra** [comment]
Marked as closed with additional information in 0.1.1
