### ISSUE TITLE
[Suggestion] Set quests to not consume needed materials

### ISSUE THREAD

**Issue by jolandepoel** [Alnarra/WaySouls#3]
In the first few quests, 'consume item' is set to Yes, which makes you lose the item the subsequent quest asks for. It is rather illogical.

For example: for the 'make a furnace' quest, the quest text refers to 'The 8 cobblestone you just collected', but since you had to turn those 8 cobblestone in, you no longer have them. And have to get 8 more cobblestone. Same for similar quests like the get a coal, but then the quest consumes the coal, and then you have to make a torch with that coal. Those are not much of a problem, aside from the inconsistency in the text, but I'm not turning in my iron ore. 

Just as an aside: loving the pack, keep polishing :)

**Comment by Alnarra** [comment]
Quest should no longer consume materials, someone let me know if they find one that does.
