### ISSUE TITLE
Issue with Wildwood Quiver

### ISSUE THREAD

**Issue by LethiasWVR** [Alnarra/WaySouls#7]
I made the wildwood bow and wildwood quiver from roots. When I use them together, I get "Bewitchment has encountered an error" and an arrow is consumed, though no arrow is fired. 
Upon testing, it seems to happen with whatever bow I use. 
Below is the log generated by this message. 
[Bewitchment Issue Log.txt](https://github.com/Alnarra/WaySouls/files/3715296/Bewitchment.Issue.Log.txt)

The only exception was the Abyssalcraft bow. That one fired, but consumed the entire quiver and everything inside it instead of a single arrow, and generated the error with the below log.
[Abyssalcraft Bow.txt](https://github.com/Alnarra/WaySouls/files/3715295/Abyssalcraft.Bow.txt)

**Comment by Alnarra** [comment]
So far as I can tell this SEEMS to be fixed, was using this a lot on the PTR today and I think Bewitchment must have nipped whatever was causing this in the bud
